Repository coreos/coreos-assembler, pull requests merged in 2019-07, with the labels that each got.

#613 src/cmd-buildupload: upload release.json when running non-legacy
  src/cmd-buildupload
Labels: hold

#626 [backport] cosalib/build.py: Add temp work directory functionality
  src/cosalib/build.py
Labels: branch/rhcos-4.2

#661 src/oscontainer.py: Add pkglist.txt to container root
  src/oscontainer.py
Labels: bug

#665 src/oscontainer.py: Add pkglist.txt to container root
  src/oscontainer.py
Labels: branch/rhcos-4.2

#666 oscontainer: Sort NEVRAs before dumping pkglist.txt
  src/oscontainer.py
Labels: branch/rhcos-4.2
