Repository coreos/coreos-assembler, pull requests merged in 2020-05, with the labels that each got.

#1415 mantle/qemu: Set a short hostname
  mantle/platform/cluster.go
  mantle/platform/machine/unprivqemu/cluster.go
Labels: approved, lgtm

#1416 Add qemu API to stream journal, use it in devshell
  mantle/cmd/kola/devshell.go
  mantle/platform/qemu.go
Labels: approved, lgtm

#1419 installer: More code cleanup
  src/cmd-buildextend-installer
Labels: approved, lgtm

#1421 dockerfile: drop install_tang step, cleanup after PR#1407
  Dockerfile
Labels: approved, lgtm

#1422 fcos.upgrade.basic: only force updates on if required
  mantle/kola/tests/rpmostree/deployments.go
  mantle/kola/tests/upgrade/basic.go
  mantle/kola/tests/util/rpmostree.go
Labels: approved, lgtm

#1425 testiso: two small patches
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm

#1107 upload-oscontainer: New command
  src/cmd-oscontainer
  src/cmd-upload-oscontainer
  src/coreos-assembler
Labels: approved, lgtm, size/L

#1426 cmdlib: default to JSON for base lockfile
  src/cmdlib.sh
Labels: approved, lgtm

#1428 kola: Write ignition-virtio-dump.txt to test dir
  mantle/platform/machine/unprivqemu/machine.go
  mantle/platform/qemu.go
  mantle/platform/util.go
Labels: approved

#1418 buildextend-live: turn on osmet packing by default
  .cci.jenkinsfile
  src/cmd-buildextend-installer
Labels: approved, lgtm

#1427 Add cosa supermin-shell
  src/cmd-supermin-shell
  src/cmdlib.sh
Labels: approved, lgtm

#1429 mantle: bump Ignition to 2.3.0
  mantle/go.mod
  mantle/go.sum
  mantle/vendor/github.com/coreos/go-systemd/v22/unit/deserialize.go
  mantle/vendor/github.com/coreos/go-systemd/v22/unit/escape.go
  mantle/vendor/github.com/coreos/go-systemd/v22/unit/option.go
  mantle/vendor/github.com/coreos/go-systemd/v22/unit/serialize.go
  mantle/vendor/github.com/coreos/ignition/v2/config/merge/merge.go
  mantle/vendor/github.com/coreos/ignition/v2/config/shared/errors/errors.go
  mantle/vendor/github.com/coreos/ignition/v2/config/shared/validations/unit.go
  mantle/vendor/github.com/coreos/ignition/v2/config/v3_0/types/unit.go
  mantle/vendor/modules.txt
Labels: approved, lgtm

#1432 cmdlib: Lower cost of cosa RPM overrides repo
  src/cmdlib.sh
Labels: approved, lgtm

#1423 Iso initramfs split prep
  src/cmd-buildextend-installer
Labels: approved, lgtm

#1329 kola/tests/ignition: add test for checking journald logs
  mantle/kola/tests/ignition/journaldEntry.go
Labels: approved, lgtm

#1439 mantle: Build binaries in parallel
  mantle/Makefile
Labels: approved, lgtm

#1440 kola: Support distros and tags in external test metadata
  mantle/kola/harness.go
Labels: approved, lgtm

#1436 kola: Add option to configure RAM
  mantle/cmd/kola/options.go
  mantle/platform/machine/unprivqemu/cluster.go
  mantle/platform/machine/unprivqemu/flight.go
Labels: approved, lgtm

#1442 Exclude rhcos distro from the journaldEntry test
  mantle/kola/tests/ignition/journaldEntry.go
Labels: approved, lgtm

#903 runc: New command
  src/cmd-runc
Labels: approved, lgtm

#1433 buildinitramfs-fast: New command to iterate on initramfs quickly
  src/cmd-buildinitramfs-fast
Labels: approved, lgtm

#1443 buildextend-live: Squash unused variable
  src/cmd-buildextend-installer
Labels: approved, lgtm

#1445 Revert "mantle: Build binaries in parallel"
  mantle/Makefile
Labels: approved, lgtm

#1420 installer: Put rootfs on ISO
  src/cmd-buildextend-installer
Labels: approved, lgtm

#1449 kola: Avoid losing "external" tag
  mantle/kola/harness.go
Labels: approved, lgtm

#1441 kola: Support loading tests from /usr/lib/coreos-assembler/tests/kola
  Makefile
  mantle/cmd/kola/kola.go
  mantle/kola/README-kola-ext.md
  mantle/kola/harness.go
Labels: approved, lgtm

#1447 qemu: IgnoreOnIsolate=true for journal streaming
  mantle/platform/qemu.go
Labels: approved, lgtm

#1450 create_disk: Add known UUIDs for /boot and /root
  src/create_disk.sh
Labels: approved, lgtm

#1453 testiso: Gather logs
  .cci.jenkinsfile
  mantle/cmd/kola/testiso.go
  mantle/platform/metal.go
Labels: approved, lgtm

#1455 mantle: Remove setenforce 1 by default
  mantle/kola/harness.go
  mantle/kola/register/register.go
  mantle/platform/platform.go
  mantle/platform/util.go
Labels: approved, lgtm

#1454 mantle/ore: gcloud: fix error detection, add some error checking
  mantle/cmd/ore/gcloud/upload.go
Labels: approved, do-not-merge/work-in-progress

#1446 mantle/ore: gcloud: add ability to attach license to image
  mantle/cmd/ore/gcloud/upload.go
  src/cosalib/gcp.py
Labels: approved

#1458 cmdlib: Don't hardcode manifest path in overrides
  src/cmdlib.sh
Labels: approved, lgtm

#1460 oscontainer: use workdir as temporary directory if provided
  src/oscontainer.py
Labels: approved, lgtm

#1461 cmd-kola: also detect --platform=
  src/cmd-kola
Labels: approved, lgtm

#1465 cmd-oscontainer: put workdir in cache qcow2 in unprivileged path
  src/cmd-oscontainer
  src/cmd-upload-oscontainer
  src/supermin-init-prelude.sh
Labels: approved, lgtm

#1467 kola: Add RHCOS LUKS upgrade test
  mantle/cmd/kola/kola.go
  mantle/kola/tests/rhcos/upgrade.go
Labels: approved, lgtm

#1462 testiso: Also capture initramfs virtio dumps
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm

#1472 kola: Replace download code with executing coreos-installer
  mantle/cmd/kola/kola.go
  mantle/sdk/download.go
Labels: approved, lgtm

#1466 testiso: Fix iso-install and iso-live-login for ppc64le
  mantle/cmd/kola/testiso.go
  mantle/platform/metal.go
  mantle/platform/qemu.go
  src/cmd-buildextend-installer
Labels: approved, lgtm

#1473 cmdlib: Stop parsing rojig/license
  src/cmdlib.sh
Labels: approved, lgtm

#1471 mantle: Move the FCOS stream URL from kola into mantle
  mantle/cmd/kola/kola.go
  mantle/fcos/metadata.go
Labels: approved, lgtm

#1468 kola: add gce support for --find-parent-image
  mantle/cmd/kola/kola.go
  mantle/cosa/build.go
Labels: approved

#1476 kola: don't error if external tests directory doesn't exist
  mantle/kola/harness.go
Labels: approved, lgtm

#1470 Remove dead code relating to detecting Ignition version
  mantle/cmd/kola/kola.go
  src/cmd-meta
  src/cmd-virt-install
  src/cmdlib.sh
  src/cosalib/cmdlib.py
Labels: approved, lgtm

#1475 testiso: Fix use of global `outputDir`
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm

#1373 grub: de-hardcode firstboot network configuration
  src/cmd-buildextend-metal
  src/create_disk.sh
  src/gf-platformid
  src/grub.cfg
Labels: approved, lgtm

#1478 kola: Add --no-net flag
  mantle/cmd/kola/options.go
  mantle/kola/harness.go
Labels: approved, lgtm

#1477 mantle/ore: gcloud: support specifying multiple image licenses
  mantle/cmd/ore/gcloud/upload.go
  mantle/platform/api/gcloud/image.go
  src/cosalib/gcp.py
Labels: approved, lgtm, ¯\_(ツ)_/¯

#1480 supermin-shell: Support passing through qemu arguments
  src/cmd-supermin-shell
Labels: approved, lgtm

#1481 testiso: Prune test scenarios for ppc64le/s390x
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm

#1482 create_disk: Ensure filesystem journal on rootfs is clean
  src/create_disk.sh
Labels: approved, lgtm

#1479 disk/s390x: inject firstboot kargs (ignition-network-kcmdline)
  src/create_disk.sh
  src/gf-platformid
Labels: approved, lgtm

#1484 kola/qemu: Pass ignition via blk device on non-fw_cfg platforms by default
  mantle/platform/qemu.go
Labels: approved, lgtm

#1485 Use shutil.move over os.rename in python code.
  src/cmd-buildextend-installer
  src/cmd-compress
  src/cmd-sign
  src/cmd-upload-oscontainer
  src/cosalib/cmdlib.py
  src/cosalib/digitalocean.py
  src/cosalib/qemuvariants.py
Labels: approved, lgtm

#1483 osmet-pack: Mount RHCOS LUKS rootfs
  src/osmet-pack
Labels: approved, lgtm

#1486 buildextend-live: check exit code of cpio/find/gzip
  src/cmd-buildextend-installer
Labels: approved, lgtm

#1487 buildextend-live: use `find . -mindepth 1` for cpio
  src/cmd-buildextend-installer
Labels: approved, lgtm

#1488 osmet-pack: patches for running in supermin
  src/osmet-pack
Labels: approved, lgtm

#1490 testiso: Tweak qemu memory for s390x
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm

#1491 Dockerfile: Switch to f32
  Dockerfile
Labels: approved, lgtm
