Repository coreos/coreos-assembler, pull requests merged in 2020-02, with the labels that each got.

#1099 Make PreP partition the first partition for ppc64le
  src/create_disk.sh
Labels: branch/rhcos-4.3

#1104 oscontainer: Add support for --display-name
  src/oscontainer.py
Labels: approved, lgtm

#1093 ore,koji: Remove timestamps from Python log formats
  src/cmd-koji-upload
  src/cmd-ore-wrapper
Labels: approved, lgtm, size/XS

#1102 refactor fedora message sending into cosalib/fedora_messaging_request.py
  src/cmd-sign
  src/cosalib/fedora_messaging_request.py
Labels: approved, lgtm, size/L

#1105 create_disk: fix UEFI secure boot
  src/create_disk.sh
Labels: approved, bug, lgtm, size/M

#1106 ci: Run --basic-qemu-scenarios
  .cci.jenkinsfile
Labels: approved, lgtm, size/XS

#1111 disk,cli: Remove timestamp from logging
  src/cmd-artifact-disk
  src/cosalib/cli.py
Labels: approved, lgtm, size/XS

#1113 Dockerfile: Blow out quay.io cache
  Dockerfile
Labels: approved, lgtm, size/XS

#1109 create_disk: put $ignition_firstboot last on kernel command line
  src/create_disk.sh
Labels: approved, lgtm, size/XS

#1114 src/cosalib: don't always force uploads for aws & aliyun
  src/cosalib/aliyun.py
  src/cosalib/aws.py
Labels: approved, lgtm, size/S

#1116 cmdlib: Require automatic-version-prefix in manifest
  src/cmdlib.sh
Labels: approved, lgtm, size/XS

#1112 test-coreos-installer: Use kola qemuexec
  src/cmd-test-coreos-installer
Labels: approved, lgtm, size/XS

#1103 qemuvariants: simplify VMware OVA generation by using callback
  src/cosalib/cmdlib.py
  src/cosalib/qemuvariants.py
  src/cosalib/vmware.py
Labels: approved, size/M

#1120 schema: use liberal pattern for FCOS parent version.
  src/schema/v1.json
Labels: approved, lgtm, size/XS

#1118 qemuvariants: add ibmcloud
  src/cmd-buildextend-ibmcloud
  src/coreos-assembler
  src/cosalib/qemuvariants.py
Labels: approved, lgtm, size/S

#1123 build.sh: Contents of /etc/sudoers.d need not to be world writable
  build.sh
Labels: approved, lgtm, size/XS

#1124 [4.2] Dockerfile: blow out quay.io cache
  Dockerfile
Labels: branch/rhcos-4.2, lgtm, size/XS

#1126 Add `cosa list` to list basic info of local builds
  src/cmd-list
  src/coreos-assembler
  src/cosalib/builds.py
Labels: approved, lgtm, size/M

#1128 Fix e2fsck on boot partition for ppc64le
  src/gf-platformid
Labels: approved, lgtm, ok-to-test, size/XS

#1131 qemuvariants: produce fixed disks for Azure
  src/cosalib/cmdlib.py
  src/cosalib/qemuvariants.py
  tests/test_cosalib_cmdlib.py
Labels: approved, lgtm, size/S

#1027 run: Use kola qemuexec, drop ssh support
  src/cmd-run
Labels: approved, lgtm, size/L

#1132 Support coreos installer test for non-x86 arches starting with ppc64le
  src/cmd-test-coreos-installer
Labels: approved, lgtm, ok-to-test, size/M

#1134 schema: add missing dasd definitions
  src/schema/v1.json
Labels: approved, lgtm, size/M

#1135 cosalib/build.py: fix invalid sha256sum key to sha256
  src/cosalib/build.py
Labels: approved, lgtm, size/XS

#1136 cosalib/vmware.py: fix OVA generation to meet spec
  src/cosalib/vmware.py
Labels: approved, lgtm, size/S

#1137 deps: Add coreos-installer
  src/deps.txt
Labels: approved, lgtm, size/XS

#1138 cmd-meta: Add --ignition-version
  src/cmd-meta
Labels: approved, lgtm, size/XS

#1143 qemuvariants: always ship tarfiles with uid/gid=0
  src/cosalib/qemuvariants.py
Labels: approved, lgtm, size/XS

#1144 gf-platformid: Add firstboot options before zipl rerun for s390x
  src/create_disk.sh
  src/gf-platformid
Labels: approved, lgtm, ok-to-test, size/XS

#1145 gf-platformid: Add firstboot options before zipl rerun for s390x
  src/create_disk.sh
  src/gf-platformid
Labels: lgtm, ok-to-test, size/XS

#1148 Revert "grub.cfg: set ip=dhcp,dhcp6"
  src/create_disk.sh
  src/gf-platformid
  src/grub.cfg
Labels: approved, lgtm, size/XS

#1147 schema: clean-up for use with schematyper
  src/schema/v1.json
Labels: approved, lgtm, size/XXL

#1150 build-sys: Add SKIPMANTLE environment variable
  Makefile
Labels: approved, lgtm, size/XS

#1127 Add exoscale provider
  src/cmd-buildextend-exoscale
  src/coreos-assembler
  src/cosalib/cli.py
  src/cosalib/exoscale.py
  src/cosalib/qemuvariants.py
  src/schema/v1.json
Labels: approved, hold, lgtm, needs-ok-to-test, size/M

#1139 Support coreos-installer test for s390x
  src/cmd-test-coreos-installer
Labels: approved, lgtm, ok-to-test, size/L

#1154 buildroot: support list of spec files to builddep
  src/buildroot-buildreqs.txt
  src/buildroot-specs.txt
  src/install-buildroot.sh
Labels: approved, lgtm, size/XS

#1155 buildroot: Remove libdnf's requirements in favor of rpm-ostree
  src/buildroot-buildreqs.txt
Labels: approved, lgtm, size/XS

#1178 mantle: Tweak schema generation script to use local cosa
  mantle/generate
Labels: approved, lgtm, size/XS

#1179 Use sdk.TargetIgnitionVersionFromName() from mantle
  mantle/cmd/kola/kola.go
  src/cosalib/cmdlib.py
Labels: approved, lgtm, size/M

#1180 Adopt mantle's (orig CoreOS) code of conduct
  code-of-conduct.md
Labels: approved, lgtm, size/XS

#1181 kola: Use runE
  mantle/cmd/kola/kola.go
Labels: approved, lgtm, size/M

#1183 mantle: Add .gitattributes for vendor/
  mantle/.gitattributes
Labels: approved, lgtm, size/XS

#1184 cosa:Generate bootable installer iso for ppc64le
  src/cmd-buildextend-installer
  src/deps-ppc64le.txt
Labels: approved, lgtm, ok-to-test, size/S

#1185 kola: Cleanup scpKolet a bit
  mantle/kola/harness.go
Labels: approved, lgtm, size/S
