Repository coreos/coreos-assembler, pull requests merged in 2020-06, with the labels that each got.

#1493 ci: run on Fedora 32 image
  .cci.jenkinsfile
Labels: approved, lgtm

#1494 deps: Add grub2-tools-extra on ppc64le for grub2-mkrescue
  src/deps-ppc64le.txt
Labels: approved, lgtm

#1497 build: Downgrade cryptsetup to 2.30-1.fc32
  build.sh
Labels: approved, lgtm

#1499 qemu: Wait until swtpm starts up
  mantle/platform/qemu.go
Labels: approved, lgtm

#1504 README-devel.md: Document `oc rsync` trick
  README-devel.md
Labels: approved, lgtm

#1492 kola: Support inline metadata JSON
  mantle/kola/README-kola-ext.md
  mantle/kola/harness.go
Labels: approved, lgtm

#1512 [4.3] oscontainer backport
  src/cmd-oscontainer
  src/cmd-upload-oscontainer
  src/oscontainer.py
Labels: branch/rhcos-4.3, lgtm

#1507 cmd-build: add --parent-build to replace --parent
  mantle/cosa/cosa_v1.go
  mantle/cosa/schema_doc.go
  src/cmd-build
  src/schema/v1.json
Labels: approved, lgtm

#1513 qemu: Add an API to request restricted networking
  mantle/platform/qemu.go
Labels: approved, lgtm

#1509 testiso: add ssh key info in ignition config for testing live ISO/PXE artifacts
  mantle/cmd/kola/devshell.go
  mantle/cmd/kola/testiso.go
  mantle/util/common.go
Labels: approved, lgtm

#1515 cosa alias: Add section on how to run multiple cosa instances
  README.md
Labels: approved, lgtm

#1516 testiso: lower install timeout to 10m
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm

#1519 Use shutil.move over os.rename in python code.
  src/cmd-buildextend-installer
  src/cmd-compress
  src/cmd-sign
  src/cmd-upload-oscontainer
  src/cosalib/cmdlib.py
  src/cosalib/digitalocean.py
  src/cosalib/qemuvariants.py
Labels: approved

#1520 mantle/kola: correct error message from kola testiso
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm

#1517 metal: don't redirect coreos-installer output to console
  mantle/platform/metal.go
Labels: approved, lgtm

#1521 osmet-pack: Remove unnecessary duplicate udev invocations
  src/osmet-pack
Labels: approved, lgtm

#1523 kola: switch qemuoptions to bios for all arches except aarch64 and x86 for metal 4k
  mantle/cmd/kola/options.go
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm

#1529 Mark parent commit as partial and prune tmp/repo more aggressively
  src/cmd-build
Labels: approved, lgtm

#1522 tests: Remove sysusers test that now lives in fedora-coreos-config
  mantle/kola/README.md
  mantle/kola/registry/registry.go
  mantle/kola/tests/systemd/sysusers.go
Labels: approved, lgtm

#1531 upload-oscontainer: Automatically inject --display-name
  src/cmd-upload-oscontainer
Labels: approved, lgtm

#1535 [4.5] upload-oscontainer: Automatically inject --display-name
  src/cmd-upload-oscontainer
Labels: approved, branch/rhcos, lgtm

#1536 [4.4] upload-oscontainer: Automatically inject --display-name
  src/cmd-upload-oscontainer
Labels: approved, branch/rhcos, lgtm

#1533 testiso: fix legacy-install scenario
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm

#1537 koji-upload: Use builds/ for tempdir
  src/cmd-koji-upload
Labels: approved, lgtm

#1538 mantle: change vsmt default value for Power
  mantle/platform/qemu.go
Labels: approved, lgtm

#1541 upload-oscontainer: Correctly strip quotes from name
  src/cmd-upload-oscontainer
Labels: approved, lgtm

#1528 kola: Support the Debian autopkgtest reboot API
  .cci.jenkinsfile
  ci/run-kola-self-tests
  mantle/cmd/kolet/kolet.go
  mantle/kola/harness.go
  tests/kola-ci-self/tests/kola/autopkgtest-reboot
Labels: approved, lgtm

#1539 build: Downgrade cryptsetup to 2.2.1-1.fc31
  build.sh
Labels: approved, lgtm, ok-to-test

#1540 build: Downgrade cryptsetup to 2.2.1-1.fc31
  build.sh
Labels: approved, lgtm, ok-to-test

#1542 [4.5] upload-oscontainer: Correctly strip quotes from name
  src/cmd-upload-oscontainer
Labels: approved, branch/rhcos, lgtm

#1544 [4.4] upload-oscontainer: Correctly strip quotes from name
  src/cmd-upload-oscontainer
Labels: approved, branch/rhcos, lgtm

#1546 README.md: Add a note about `--net=host` here.
  README.md
Labels: approved, lgtm

#1545 entrypoint: Use mount --bind for /sys/fs/selinux
  src/coreos-assembler
Labels: approved, lgtm

#1534 build.sh: preserve s390-base.rpm package from uninstalling
  build.sh
Labels: approved, lgtm, ok-to-test

#1525 kola/qemuexec: add option to create additional disks
  mantle/cmd/kola/qemuexec.go
Labels: approved, lgtm

#1548 kola: Remove stray stdout logging
  mantle/cmd/kolet/kolet.go
  mantle/kola/harness.go
Labels: approved, lgtm

#1547 cmd-oc-adm-release: new tool for release origin/ocp payloads
  src/cmd-oc-adm-release
  src/coreos-assembler
Labels: approved, lgtm

#1551 Dockerfile: tickle Quay for rebuild
  Dockerfile
Labels: approved, lgtm

#1552 cmd-sign: verify signature using specific GPG key
  src/cmd-sign
Labels: approved, lgtm

#1556 README-kola-ext: Document new autopkgtest reboot API
  mantle/kola/README-kola-ext.md
Labels: approved, lgtm

#1557 kola: tests/crio: Update for 1.18 release compatibility
  mantle/kola/tests/crio/crio.go
Labels: approved, lgtm

#1558 kola: Use Ignition v3 -> v2 translation for more tests
  mantle/kola/tests/rhcos/luks.go
  mantle/kola/tests/rhcos/sssd.go
  mantle/kola/tests/rhcos/upgrade.go
Labels: approved, lgtm

#1553 Fix libguestfish for Power
  src/libguestfish.sh
Labels: approved, lgtm

#1559 [rhcos-4.5] kola: tests/crio: Update for 1.18 release compatibility
  mantle/kola/tests/crio/crio.go
Labels: approved, lgtm

#1555 build: Downgrade cryptsetup to 2.2.1-1.fc31
  build.sh
Labels: approved, lgtm, ok-to-test

#1560 README-devel.md: Update with more tips
  README-devel.md
Labels: approved, lgtm

#1562 kola: tests/crio: Fixup 1.18 test update
  mantle/kola/tests/crio/crio.go
Labels: approved, lgtm

#1563 kola: tests/crio: Fixup 1.18 test update
  mantle/kola/tests/crio/crio.go
Labels: approved, lgtm

#1567 Add cosa commit and rhcos commit as labels in oscontainer
  src/oscontainer.py
Labels: approved, lgtm
