Repository coreos/coreos-assembler, pull requests merged in 2020-03, with the labels that each got.

#1187 [rhcos-4.3] cosa:Generate bootable installer iso for ppc64le
  src/cmd-buildextend-installer
  src/deps-ppc64le.txt
Labels: lgtm, ok-to-test, size/S

#1189 plume: Remove unused CL code
  mantle/cmd/plume/prerelease.go
Labels: approved, lgtm, size/M

#1168 kola: Add testiso command
  mantle/cmd/kola/testiso.go
  src/cmd-test-coreos-installer
Labels: approved, lgtm, size/L

#1194 kola: Rework scpKolet and dropFile to be generic APIs
  mantle/kola/cluster/cluster.go
  mantle/kola/harness.go
  mantle/kola/tests/crio/crio.go
  mantle/kola/tests/docker/docker.go
  mantle/kola/tests/upgrade/basic.go
Labels: approved, lgtm, size/S

#1193 mantle: Don't delete agent dir if MANTLE_SSH_DIR is specified
  mantle/network/ssh.go
Labels: approved, lgtm, size/M

#1188 kola: Port more main functions to Run*E*
  mantle/cmd/kola/bootchart.go
  mantle/cmd/kola/console.go
  mantle/cmd/kola/kola.go
  mantle/cmd/kola/qemuexec.go
  mantle/cmd/kola/spawn.go
Labels: approved, lgtm, size/M

#1196 kola/testiso: Port to Run*E*
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm, size/S

#1191 README-devel.md: drop mantle bump instructions
  README-devel.md
Labels: approved, lgtm, size/M

#1198 build-sys: Remove SKIPMANTLE environment variable
  Makefile
Labels: approved, lgtm, size/XS

#1199 schema: Add live-{kernel,initramfs,iso}
  mantle/cosa/cosa_v1.go
  src/schema/v1.json
Labels: approved, lgtm, size/M

#1200 schema: Fix duplicate key in overrides-active
  src/schema/v1.json
Labels: approved, lgtm, size/XS

#1190 tree: delete Dependabot config
  .dependabot/config.yml
Labels: approved, lgtm, size/XS

#1202 mantle: update Ignition spec detection for RHCOS 4.5
  mantle/sdk/ignversion.go
  src/cmd-run
Labels: approved, lgtm, size/XS

#1201 ci: Remove .travis.yml
  .travis.yml
Labels: approved, lgtm, size/S

#1204 End schema complexity experiment; simplify the schema for x-lang support
  mantle/cosa/cosa_v1.go
  src/schema/v1.json
Labels: approved, lgtm, size/L

#1209 mantle/schematyper: harden for `go mod` commands
  mantle/Makefile
  mantle/build
  mantle/cosa/cosa_v1.go
  mantle/go.mod
  mantle/go.sum
  mantle/schema-generate
  mantle/schematyper/LICENSE
  mantle/schematyper/README.md
  mantle/schematyper/deps.go
  mantle/schematyper/generator.go
  mantle/schematyper/metaschema.json
  mantle/schematyper/metaschema_schematype.go
  mantle/vendor/github.com/alecthomas/template/example_test.go
  mantle/vendor/github.com/alecthomas/template/examplefiles_test.go
  mantle/vendor/github.com/alecthomas/template/examplefunc_test.go
  mantle/vendor/github.com/alecthomas/template/exec_test.go
  mantle/vendor/github.com/alecthomas/template/multi_test.go
  mantle/vendor/github.com/alecthomas/template/parse/lex_test.go
  mantle/vendor/github.com/alecthomas/template/parse/parse_test.go
  mantle/vendor/github.com/alecthomas/template/testdata/file1.tmpl
  mantle/vendor/github.com/alecthomas/template/testdata/file2.tmpl
  mantle/vendor/github.com/alecthomas/template/testdata/tmpl1.tmpl
  mantle/vendor/github.com/alecthomas/template/testdata/tmpl2.tmpl
  mantle/vendor/github.com/gedex/inflector/example_test.go
  mantle/vendor/github.com/gedex/inflector/inflector_test.go
  mantle/vendor/github.com/idubinskiy/schematyper/.gitignore
  mantle/vendor/github.com/idubinskiy/schematyper/stringset/stringset_test.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/_examples/chat1/main.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/_examples/chat2/main.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/_examples/completion/main.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/_examples/curl/main.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/_examples/modular/main.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/_examples/ping/main.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/app_test.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/args_test.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/cmd/genvalues/main.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/cmd_test.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/completions_test.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/examples_test.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/flags_test.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/parser_test.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/parsers_test.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/usage_test.go
  mantle/vendor/gopkg.in/alecthomas/kingpin.v2/values_test.go
  mantle/vendor/modules.txt
Labels: approved, lgtm, size/XXL

#1210 run: Explicitly enable usermode networking
  src/cmd-run
Labels: approved, lgtm, size/XS

#1212 mantle: Stop cleaning every build
  mantle/Makefile
Labels: approved, lgtm, size/XS

#1211 run/kola-qemuexec: Add DHCP hostname support
  mantle/cmd/kola/qemuexec.go
  mantle/platform/qemu.go
  src/cmd-run
Labels: approved, lgtm, size/S

#1213 schema: Strip absolute filename
  mantle/build
  mantle/cosa/cosa_v1.go
Labels: approved, lgtm, size/XS

#1208 mantle: kola: use by-partuuid instead of by-partlabel for mount test
  mantle/kola/tests/ignition/mount.go
Labels: approved, lgtm, ok-to-test, size/S

#1216 Revert "Revert "grub.cfg: set ip=dhcp,dhcp6""
  src/create_disk.sh
  src/gf-platformid
  src/grub.cfg
Labels: approved, lgtm, size/XS

#1221 testiso: Validate that we have a `metal` image
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm, size/S

#1217 kola/spawn: restrict --reconnect to qemu platform
  mantle/cmd/kola/spawn.go
Labels: approved, lgtm, size/XS

#1220 mantle/*: Add SilenceUsage to all CLI entrypoints
  mantle/cmd/kola/bootchart.go
  mantle/cmd/kola/console.go
  mantle/cmd/kola/kola.go
  mantle/cmd/kola/qemuexec.go
  mantle/cmd/kola/testiso.go
  mantle/cmd/ore/aliyun/copy-image.go
  mantle/cmd/ore/aliyun/create-image.go
  mantle/cmd/ore/aliyun/delete.go
  mantle/cmd/ore/aliyun/list-regions.go
  mantle/cmd/ore/aws/copy-image.go
  mantle/cmd/ore/aws/gc.go
  mantle/cmd/ore/aws/initialize.go
  mantle/cmd/ore/aws/list-regions.go
  mantle/cmd/ore/aws/upload.go
  mantle/cmd/ore/azure/create-image-arm.go
  mantle/cmd/ore/azure/create-image.go
  mantle/cmd/ore/azure/delete-image.go
  mantle/cmd/ore/azure/gc.go
  mantle/cmd/ore/azure/replicate-image.go
  mantle/cmd/ore/azure/share-image.go
  mantle/cmd/ore/azure/unreplicate-image.go
  mantle/cmd/ore/do/create-image.go
  mantle/cmd/ore/do/delete-image.go
  mantle/cmd/ore/do/delete-keys.go
  mantle/cmd/ore/do/gc.go
  mantle/cmd/ore/do/list-keys.go
  mantle/cmd/ore/esx/create-base.go
  mantle/cmd/ore/esx/remove-base.go
  mantle/cmd/ore/gcloud/gc.go
  mantle/cmd/ore/openstack/create.go
  mantle/cmd/ore/openstack/delete.go
  mantle/cmd/ore/openstack/gc.go
  mantle/cmd/ore/packet/delete-keys.go
  mantle/cmd/ore/packet/gc.go
  mantle/cmd/ore/packet/list-keys.go
  mantle/cmd/plume/prerelease.go
Labels: approved, lgtm, size/M

#1219 kola/qemu: Support injecting kernel network arguments
  mantle/cmd/kola/qemuexec.go
  mantle/platform/qemu.go
Labels: approved, lgtm, size/M

#1218 kola/switch-kernel: add a test for switching between rt and default kernel
  mantle/cmd/kola/switchkernel.go
Labels: approved, size/L

#1223 mantle/*: Use errors.Wrapf() in more places
  mantle/cmd/kola/spawn.go
  mantle/harness/suite.go
  mantle/kola/harness.go
  mantle/platform/journal.go
  mantle/platform/machine/azure/flight.go
  mantle/platform/machine/esx/machine.go
  mantle/platform/platform.go
  mantle/platform/qemu.go
Labels: approved, lgtm, size/M

#1222 mantle: Generate ssh-config in output dir
  mantle/platform/cluster.go
Labels: approved, lgtm, size/M

#1224 libguestfish.sh: actually use --ro for read-only runs
  src/libguestfish.sh
Labels: approved, lgtm, size/XS

#1195 sdk: Trim away lots of CL stuff
  mantle/cmd/plume/prerelease.go
  mantle/sdk/create.go
  mantle/sdk/download.go
  mantle/sdk/enter.go
  mantle/sdk/repo.go
Labels: approved, lgtm, size/XL

#1226 Revert "libguestfish.sh: actually use --ro for read-only runs"
  src/libguestfish.sh
Labels: approved, lgtm, size/XS

#1228 kola: Use --cosa-build for Ignition version inference automatically
  mantle/cmd/kola/options.go
  mantle/sdk/ignversion.go
  src/cmd-kola
Labels: approved, lgtm, size/S

#1230 mantle: Don't crash if there's no port in spawned machine
  mantle/platform/cluster.go
Labels: approved, lgtm, size/S

#1232 mantle: Really avoid crashing if no port is set for SSH
  mantle/platform/cluster.go
Labels: approved, lgtm, size/XS

#1227 kola: Use by-partlabel for mount tests except on s390x
  mantle/kola/tests/ignition/mount.go
  mantle/util/common.go
Labels: approved, lgtm, ok-to-test, size/L

#1233 Allow having only an overrides lockfile
  src/cmd-build
  src/cmd-fetch
Labels: approved, lgtm, size/M

#1234 kola/switchkernel: Add SilenceUsage
  mantle/cmd/kola/switchkernel.go
Labels: approved, lgtm, size/XS

#1238 mantle: Actually display schema errors
  mantle/cosa/build.go
Labels: approved, lgtm, size/XS

#1237 cmd-run: print kola qemuexec command before running
  src/cmd-run
Labels: approved, lgtm

#1231 mantle: Move core metal logic into platform/, use for testiso
  mantle/cmd/kola/testiso.go
  mantle/platform/metal.go
Labels: approved, lgtm, size/XL

#1243 ci: Test `kola testiso`
  .cci.jenkinsfile
Labels: approved, lgtm

#1130 Add support for 4k metal images
  build.sh
  mantle/cmd/kola/options.go
  mantle/cmd/kola/qemuexec.go
  mantle/platform/machine/unprivqemu/cluster.go
  mantle/platform/machine/unprivqemu/flight.go
  mantle/platform/qemu.go
  src/cmd-buildextend-metal
  src/cmd-buildextend-metal4k
  src/cmd-run
  src/coreos-assembler
  src/create_disk.sh
Labels: approved, lgtm, size/L

#1239 mantle/schema: use `schematyper --ptr-for-omit`
  mantle/build
  mantle/cosa/cosa_v1.go
  mantle/sdk/ignversion.go
Labels: approved, lgtm, size/M

#1247 mantle: Adjust testiso/metal for ptr values in cosa.Build
  mantle/cmd/kola/testiso.go
  mantle/platform/metal.go
Labels: approved, lgtm

#1249 build.sh: use f32-coreos-continuous for libguestfs
  build.sh
Labels: approved, lgtm

#1250 cmd-{build,fetch}: fix log message referencing wrong lockfile
  src/cmd-build
  src/cmd-fetch
Labels: approved, lgtm

#1242 mantle/kola: allow invalid meta.json as a user option
  mantle/cosa/schema.go
Labels: approved, lgtm

#1240 Move distribution detection into mantle
  mantle/cmd/kola/options.go
  mantle/sdk/distros.go
  src/cmd-kola
Labels: approved, lgtm

#1253 schema: add metal4k to the schema
  src/schema/v1.json
Labels: approved, lgtm, ok-to-test

#1252 kola: Replace run-ext-bin with `kola run -E/--exttest`
  mantle/cmd/kola/kola.go
  mantle/cmd/kolet/kolet.go
  mantle/kola/README-kola-ext.md
  mantle/kola/harness.go
  mantle/kola/register/register.go
  mantle/kola/runext.go
Labels: approved, lgtm

#1254 mantle/build: explicitly specify schematyper binary name
  mantle/build
Labels: approved, lgtm

#1256 mantle/cosa: Regenerate schema for 4knative
  mantle/cosa/cosa_v1.go
Labels: approved, lgtm

#1260 kola/fcos.users.shells: work-around root user NSS bug
  mantle/kola/tests/misc/users.go
Labels: approved, lgtm

#1257 mantle/system: Add RpmArch API
  mantle/system/arch.go
Labels: approved, lgtm

#1255 mantle/sdk: Clean out version.go
  mantle/sdk/version.go
  mantle/sdk/version_test.go
Labels: approved, lgtm

#1261 kola: Automatically add src/config/tests/kola if it exists
  src/cmd-kola
Labels: approved, lgtm

#1264 gf-platformid: Mount a temporary /dev needed for s390x when running zipl in chroot
  src/gf-platformid
Labels: approved, lgtm, ok-to-test

#1262 cmd-build: Add hack for composing across refs
  src/cmd-build
Labels: approved, lgtm

#1258 mantle: Rework various bits to use new RpmArch() API
  mantle/cmd/kola/kola.go
  mantle/cmd/kola/options.go
  mantle/cmd/kola/qemuexec.go
  mantle/cmd/kola/testiso.go
  mantle/kola/tests/ignition/mount.go
  mantle/platform/machine/unprivqemu/cluster.go
  mantle/platform/metal.go
  mantle/platform/qemu.go
Labels: approved, lgtm

#1267 Move the "4k implies uefi" logic into kola
  mantle/cmd/kola/options.go
  src/cmd-run
Labels: approved, lgtm

#1269 buildextend-installer: Remove unnecessary kargs exclusions
  src/cmd-buildextend-installer
Labels: approved, lgtm

#1265 Support `cosa run --kargs`
  mantle/cmd/kola/qemuexec.go
  mantle/platform/qemu.go
  src/cmd-run
Labels: approved, lgtm

#1271 Testiso actually iso prep
  mantle/platform/metal.go
Labels: approved, lgtm

#1275 kola: Avoid SEGV if no qemu image
  mantle/cmd/kola/options.go
Labels: approved, lgtm

#1276 ci: Run testiso before test_pruning.sh
  .cci.jenkinsfile
Labels: approved, lgtm

#1277 mantle/conf: Remove Ignition spec 1 support
  mantle/platform/conf/conf.go
Labels: approved, lgtm

#1278 system/arch: Canonicalize ppc64, ppc64le => ppc64le
  mantle/system/arch.go
Labels: approved, lgtm

#1259 Teach mantle/kola how to automatically find cosa builds
  mantle/cmd/kola/options.go
  mantle/sdk/repo.go
  src/cmd-kola
Labels: approved, lgtm

#1282 kola/tests: Swith to expecting Networkmanager vs dhclient
  mantle/kola/tests/misc/network.go
Labels: approved, lgtm

#1283 kola: promote concept of sdk.LocalBuild throughout
  mantle/cmd/kola/kola.go
  mantle/cmd/kola/options.go
  mantle/cmd/kola/testiso.go
  mantle/kola/harness.go
  mantle/kola/tests/upgrade/basic.go
  mantle/platform/metal.go
  mantle/platform/platform.go
  mantle/sdk/repo.go
  src/cmd-kola
Labels: approved, lgtm

#1286 kola/qemu: Use max supported gic version on the aarch64 host
  mantle/platform/qemu.go
Labels: approved, lgtm

#1280 deps: Allow empty archful deps files
  src/deps-aarch64.txt
  src/print-dependencies.sh
Labels: approved, lgtm

#1288 cmdlib: Use -hda/-hdb instead of virtio-scsi incantations
  src/cmdlib.sh
Labels: approved, lgtm

#1284 Move Ignition conversion into qemu API
  mantle/cmd/kola/options.go
  mantle/cmd/kola/qemuexec.go
  mantle/platform/qemu.go
  src/cmd-run
Labels: approved, lgtm

#1279 kola: Use RpmArch() instead of architecture()
  mantle/Makefile
  mantle/kola/harness.go
Labels: approved, lgtm, ok-to-test

#1291 mantle/qemu: Rework API to allow setting Config after creation
  mantle/cmd/kola/qemuexec.go
  mantle/platform/machine/unprivqemu/cluster.go
  mantle/platform/metal.go
  mantle/platform/qemu.go
Labels: approved, lgtm

#1285 Move 9p mount logic into QemuBuilder/qemuexec
  mantle/cmd/kola/qemuexec.go
  mantle/go.mod
  mantle/platform/conf/conf.go
  mantle/platform/qemu.go
  src/cmd-run
Labels: approved, lgtm

#1292 Revert "cmdlib: Use -hda/-hdb instead of virtio-scsi incantations"
  src/cmdlib.sh
Labels: approved, lgtm

#1293 kola: Minor arch cleanup
  mantle/kola/harness.go
Labels: approved, lgtm

#1295 aws: provide way to select source-region
  src/cmd-ore-wrapper
  src/cosalib/aws.py
Labels: approved, lgtm

#1266 kola/tests/ignition: add test for systemd instantiated units
  mantle/kola/tests/ignition/units.go
Labels: approved, lgtm

#1294 qemuexec: Support providing no config
  mantle/cmd/kola/qemuexec.go
Labels: approved, lgtm

#1303 build-sys: Only build schema if source changed
  mantle/Makefile
  mantle/build
Labels: approved, lgtm

#1304 buildextend-live: Also filter out rhcos.root kernel argument
  src/cmd-buildextend-installer
Labels: approved, lgtm
