Repository coreos/coreos-assembler, pull requests merged in 2020-10, with the labels that each got.

#1749 mantle: make kola use ecdsa SSH keys
  mantle/network/ssh.go
  mantle/platform/conf/conf_test.go
Labels: approved, lgtm

#1751 build: Remove local overrides lock when removing RPMs
  src/cmdlib.sh
Labels: approved, lgtm

#1754 src/build-deps.txt: add golint as a build dep
  src/build-deps.txt
Labels: approved, lgtm

#1755 cmd-kola: allow excluding tests for specific branch
  src/cmd-kola
Labels: approved, lgtm

#1756 mantle: kola: Update fcos.network.listeners test for Fedora 33
  mantle/kola/tests/misc/network.go
Labels: approved, lgtm

#1759 [4.5] Skip testiso for POWER
  mantle/cmd/kola/testiso.go
Labels: approved, branch/rhcos, lgtm

#1760 [4.4] Skip testiso for POWER
  mantle/cmd/kola/testiso.go
Labels: approved, branch/rhcos, lgtm

#1762 mantle: platform: update iso embed call
  mantle/platform/qemu.go
Labels: approved, lgtm

#1758 mantle: fix podman.workflow stop test
  mantle/kola/tests/podman/podman.go
Labels: approved, lgtm

#1764 buildextend-live: add osmet-pack-with-cosa-coreinst image.yaml key
  src/cmd-buildextend-live
Labels: approved, lgtm

#1765 buildextend-live: drop --legacy-pxe option
  src/cmd-buildextend-live
Labels: approved, lgtm

#1767 Revert "mantle: make kola use ecdsa SSH keys"
  mantle/network/ssh.go
  mantle/platform/conf/conf_test.go
Labels: approved, lgtm

#1753 OWNERS: Add travier
  OWNERS
Labels: approved, lgtm

#1773 entrypoint: build dep and Makefile improvement
  entrypoint/Makefile
  entrypoint/ocp/build.json
  src/deps.txt
Labels: approved, lgtm

#1770 [4.5] Revert #1759 and downgrade grub for ppc64le
  build.sh
  mantle/cmd/kola/testiso.go
Labels: approved, branch/rhcos, lgtm

#1769 [4.4] Revert #1760 and downgrade grub for ppc64le
  build.sh
  mantle/cmd/kola/testiso.go
Labels: approved, branch/rhcos, lgtm

#1768 kola/ext: bump minimum of memory to 8G on 64k page arches, ppc64le for now
  mantle/kola/harness.go
Labels: approved, lgtm

#1771 kola: don't resolve symlinks for ext test naming
  mantle/kola/harness.go
Labels: approved, lgtm

#1776 entrypoint: avoid triggering `build` at `install` time
  entrypoint/Makefile
Labels: approved, lgtm

#1763 virt-install: Only allocate Builds if --image is not passed
  src/cmd-virt-install
Labels: approved, lgtm

#1745 exttests: New container image with upstream tests
  exttests/Dockerfile
  exttests/README.md
  exttests/build.sh
Labels: approved, lgtm

#1778 kola/tests/ignition: update resource test to use different bucket
  mantle/kola/tests/ignition/resource.go
Labels: approved, lgtm

#1780 kola/tests/ignition: update resource test to use different bucket
  mantle/kola/tests/ignition/resource.go
Labels: approved, lgtm

#1781 kola/tests/ignition: update resource test to use different bucket
  mantle/kola/tests/ignition/resource.go
Labels: approved, lgtm

#1779 kola/tests/ignition: update resource test to use different bucket
  mantle/kola/tests/ignition/resource.go
Labels: approved, lgtm

#1786 cmdlib: Ensure overlay files have read-only executables
  src/cmdlib.sh
Labels: approved, lgtm

#1785 cmd-fetch: better ignore cosa overrides by default
  src/cmd-build
  src/cmd-fetch
  src/cmdlib.sh
Labels: approved, lgtm

#1791 docs/kola: mention external tests are preferred
  docs/kola/adding-tests.md
Labels: approved, lgtm

#1794 kola: deny external tests before parsing Ignition config
  mantle/kola/harness.go
Labels: approved, lgtm

#1792 kola: Support config.fcc for external tests
  docs/kola/external-tests.md
  mantle/kola/harness.go
Labels: approved, lgtm

#1798 Revert mounting /etc/pki in Supermin
  src/cmdlib.sh
  src/supermin-init-prelude.sh
Labels: approved, lgtm

#1789 Write out a ref with the build ID
  src/cmd-build
  src/cmd-prune
Labels: approved, lgtm

#1799 mantle: work around for ssh crypto policies change
  mantle/kola/tests/ignition/empty.go
  mantle/network/ssh.go
  mantle/platform/conf/conf_test.go
  mantle/platform/machine/aws/flight.go
Labels: approved, jira, lgtm

#1801 entrypoint: clean up execution of templates
  entrypoint/cmd/build.go
  entrypoint/cmd/entry.go
  entrypoint/exec/go_init.go
  entrypoint/exec/run.go
  entrypoint/ocp/build_ci_test.go
  entrypoint/ocp/builder.go
  entrypoint/ocp/builder_test.go
  entrypoint/ocp/cosa_init.go
  entrypoint/spec/clone.go
  entrypoint/spec/rhcos_jobspec_test.go
  entrypoint/spec/tmpl.go
Labels: approved, lgtm

#1803 [4.5]create_disk: remove immutable bit for s390x
  src/create_disk.sh
Labels: approved, lgtm

#1804 cmd-fetch: assuage ShellCheck
  src/cmd-fetch
Labels: approved, lgtm

#1796 [rhcos-4.3] ci: use Fedora 31 image
  .travis.yml
Labels: approved, branch/rhcos, lgtm

#1809 Dockerfile: blow out cache to force full Quay rebuild
  Dockerfile
Labels: approved, lgtm

#1806 cmdlib: stop copying resolv.conf
  src/cmdlib.sh
Labels: approved, lgtm

#1810 [4.4]create_disk: remove immutable bit for s390x
  src/create_disk.sh
Labels: approved, branch/rhcos, lgtm

#1678 Drop support for ignition-network-kcmdline
  src/cmd-buildextend-metal
  src/create_disk.sh
  src/gf-platformid
Labels: approved, lgtm

#1811 Makefile: fix minio installation
  Makefile
Labels: approved, lgtm

#1814 mantle: clean up code base
  mantle/lang/maps/sorted_test.go
Labels: approved, lgtm

#1815 kola: clean up unused plog
  mantle/kola/tests/rhcos/upgrade.go
Labels: approved, lgtm

#1818 kola: Fix various golint warnings
  mantle/cmd/kola/console.go
  mantle/cmd/kola/kola.go
  mantle/cmd/kola/qemuexec.go
  mantle/cmd/kola/spawn.go
  mantle/cmd/kola/testiso.go
Labels: approved, lgtm

#1822 kola: clean up luks
  mantle/kola/tests/rhcos/luks.go
Labels: approved, lgtm
