Repository coreos/coreos-assembler, pull requests merged in 2021-03, with the labels that each got.

#2058 Use coreos-ci-lib to run Kola QEMU
  .cci.jenkinsfile
Labels: approved, lgtm

#2056 Add COSA_SUPPRESS_DEPCHECK to turn off "rpm -q all the things"
  src/cmdlib.sh
Labels: approved, lgtm

#2060 Use coreos-ci-lib to build metal artifacts
  .cci.jenkinsfile
Labels: approved, lgtm

#2059 Gangplank: Prepare for Distributed Builds
  gangplank/cmd/pod.go
  gangplank/ocp/bc.go
  gangplank/ocp/cosa-pod.go
  gangplank/ocp/filer.go
  gangplank/ocp/return.go
  gangplank/ocp/worker.go
  gangplank/spec/stages.go
Labels: approved, lgtm

#2063 Gangplank: make podman mode errors fatal
  gangplank/ocp/bc.go
  gangplank/ocp/cosa-pod.go
Labels: approved, lgtm

#2062 Use coreos-ci-lib to run cosa commands
  .cci.jenkinsfile
Labels: approved, lgtm

#2066 Revert "mantle: Check for SELinux AVCs just like systemd failed units"
  mantle/cmd/kola/options.go
  mantle/kola/harness.go
  mantle/platform/platform.go
Labels: approved, lgtm

#2065 Use coreos-ci-lib to run `kola testiso`
  .cci.jenkinsfile
Labels: approved, lgtm

#2070 coreos.boot-mirror: only run on x86_64
  mantle/kola/tests/misc/boot-mirror.go
Labels: approved, lgtm

#2068 Use coreos-ci-lib to run parallel commands
  .cci.jenkinsfile
Labels: approved, lgtm

#2072 kola: follow symlinks when collecting external host tests
  mantle/kola/harness.go
Labels: approved, lgtm

#2073 Remove cosa_cmd function
  .cci.jenkinsfile
Labels: approved, lgtm

#2069 Gangplank: Allow access in template to JobSpec and meta.json
  gangplank/cmd/main.go
  gangplank/ocp/worker.go
  gangplank/spec/render_test.go
  gangplank/spec/stage_test.go
  gangplank/spec/stages.go
  gangplank/spec/tmpl.go
Labels: approved, lgtm

#2079 schema: Drop requirement on ostree transaction commit metadata
  docs/gangplank/api-cosa.md
  fixtures/fcos.json
  fixtures/rhcos.json
  gangplank/cosa/schema_doc.go
  gangplank/cosa/v1.go
  mantle/cosa/cosa_v1.go
  mantle/cosa/schema_doc.go
  src/schema/v1.json
Labels: approved, lgtm

#2082 Dockerfile: Blow quay.io cache to pick up newer librepo
  Dockerfile
Labels: approved, lgtm

#2075 Add support for arch-independent lockfile overrides
  src/cmd-build
  src/cmd-fetch
  src/cmdlib.sh
Labels: approved, lgtm

#2084 Gangplank: fix defer order in pod IP check
  gangplank/ocp/k8s.go
Labels: approved, lgtm

#2081 Gangplank: only return artifact if a path exists
  gangplank/cosa/build.go
Labels: approved, lgtm

#2086 cmd/init: ignore dotfiles in working directory
  src/cmd-init
Labels: approved, lgtm

#2074 Gangplank Docs: Add base docs
  docs/gangplank/README.md
  docs/gangplank/usage.md
Labels: approved

#2087 kolet: Add httpd command
  docs/kola/external-tests.md
  mantle/cmd/kolet/kolet.go
Labels: approved, lgtm

#2083 cmdlib: fix impl_rpmostree_compose for POWER
  src/cmd-buildextend-metal
  src/cmdlib.sh
  src/libguestfish.sh
Labels: approved, lgtm

#2090 Dockerfile: defenestrate Quay.io cache for new rpm-ostree release
  Dockerfile
Labels: approved, lgtm

#2089 Gangplank: allow for creating multiple artifacts in the same stage
  gangplank/spec/stages.go
Labels: approved, lgtm

#2093 Gangplank: use git date and last change for version
  gangplank/Makefile
Labels: approved, lgtm

#2094 mantle/qemu: hack around SELinux violation in virtio journal service
  mantle/platform/qemu.go
Labels: approved, lgtm

#2092 mantle/aws/images: Support building aarch64 VM images and AMI
  mantle/platform/api/aws/images.go
Labels: approved, lgtm

#2091 Gangplank: shareable minio via minio only mode
  gangplank/cmd/minio.go
  gangplank/cmd/pod.go
  gangplank/ocp/bc.go
  gangplank/ocp/filer.go
  gangplank/ocp/filer_test.go
  gangplank/ocp/pod.go
  gangplank/ocp/remotes_test.go
  gangplank/spec/jobspec.go
Labels: approved, lgtm

#2098 Remove buildroot image definition
  Dockerfile.buildroot
  src/buildroot-buildreqs.txt
  src/buildroot-reqs.txt
  src/buildroot-specs.txt
  src/install-buildroot.sh
Labels: do-not-merge/hold

#2095 Gangplank: improved dependencies for base builds
  gangplank/cmd/minio.go
  gangplank/ocp/bc.go
  gangplank/ocp/const.go
  gangplank/ocp/filer.go
  gangplank/ocp/filer_test.go
  gangplank/ocp/remotes.go
  gangplank/ocp/remotes_test.go
  gangplank/ocp/return.go
  gangplank/ocp/return_test.go
  gangplank/ocp/worker.go
  gangplank/spec/stages.go
Labels: approved

#2107 ocp: use a cluster role for Gangplank
  ocp/cosa-bc.yaml
Labels: lgtm
