Repository coreos/coreos-assembler, pull requests merged in 2021-07, with the labels that each got.

#2263 Gangplank: fixes for Minio timeouts seen in CI
  gangplank/internal/ocp/filer.go
  gangplank/internal/ocp/filer_test.go
Labels: do-not-merge/hold

#2285 docs: fix two typos
  docs/cosa.md
Labels: needs-ok-to-test

#2276 [rhcos-4.8] Gangplank: Fix jobspec bad repo test for rhcos-4.8
  gangplank/spec/jobspec.go
  gangplank/spec/jobspec_test.go
Labels: ok-to-test, okay-to-test

#2292 usage.md: minor copyediting
  docs/gangplank/usage.md
Labels: ok-to-test
