Repository coreos/coreos-assembler, pull requests merged in 2021-01, with the labels that each got.

#1985 buildextend-live: make default kargs file look the same
  src/cmd-buildextend-live
Labels: approved, lgtm

#1990 buildextend-live: hybridize live ISO for UEFI boot
  src/cmd-buildextend-live
Labels: approved, lgtm

#1991 mantle: Clean up exported functions for stream/releases
  mantle/fcos/metadata.go
Labels: approved, lgtm

#1992 plume: Rename internal variable in prep for using stream-metadata-go
  mantle/cmd/plume/release.go
Labels: approved, lgtm

#1994 buildextend-live: fix crash when running on !x86_64
  src/cmd-buildextend-live
Labels: approved, lgtm

#1996 buildextend-live: fix off-by-one calculating karg embed area size; change magic number
  src/cmd-buildextend-live
Labels: approved, lgtm

#1989 qemu: automatically inject serial console karg into ISO
  mantle/platform/qemu.go
Labels: approved, lgtm

#1993 Use coreos/stream-metadata-go
  mantle/cmd/kola/kola.go
  mantle/cmd/plume/release.go
  mantle/fcos/metadata.go
  mantle/go.mod
  mantle/go.sum
  mantle/platform/api/packet/api.go
  mantle/vendor/github.com/coreos/stream-metadata-go/LICENSE
  mantle/vendor/github.com/coreos/stream-metadata-go/fedoracoreos/fcos.go
  mantle/vendor/github.com/coreos/stream-metadata-go/fedoracoreos/internals/fcosinternals.go
  mantle/vendor/github.com/coreos/stream-metadata-go/release/release.go
  mantle/vendor/github.com/coreos/stream-metadata-go/stream/stream.go
  mantle/vendor/modules.txt
Labels: approved, lgtm

#1997 kola: Add support for `kola --stream stable -p aws ...`
  mantle/cmd/kola/options.go
  mantle/fcos/metadata.go
  mantle/platform/platform.go
Labels: approved, lgtm

#1999 docs/kola: Fix kola quickstart link
  docs/kola.md
Labels: approved, lgtm

#2001 mantle: bump Ignition to 2.9.0
  mantle/go.mod
  mantle/go.sum
  mantle/vendor/github.com/coreos/ignition/v2/config/merge/merge.go
  mantle/vendor/github.com/coreos/ignition/v2/config/shared/errors/errors.go
  mantle/vendor/github.com/coreos/ignition/v2/config/v3_0/types/filesystem.go
  mantle/vendor/github.com/coreos/ignition/v2/config/v3_0/types/partition.go
  mantle/vendor/github.com/coreos/ignition/v2/config/v3_1/types/filesystem.go
  mantle/vendor/github.com/coreos/ignition/v2/config/v3_1/types/partition.go
  mantle/vendor/github.com/coreos/ignition/v2/config/v3_2/types/filesystem.go
  mantle/vendor/github.com/coreos/ignition/v2/config/v3_2/types/partition.go
  mantle/vendor/github.com/coreos/ignition/v2/config/v3_3_experimental/types/filesystem.go
  mantle/vendor/github.com/coreos/ignition/v2/config/v3_3_experimental/types/partition.go
  mantle/vendor/modules.txt
Labels: approved, lgtm

#2006 Import FCOS trans.py that converts meta.json → release.json
  src/cmd-generate-release-meta
Labels: approved, lgtm

#2007 kola: fix RHCOS growpart test
  mantle/kola/tests/coretest/core.go
Labels: approved, lgtm

#2005 grub: make boot RAID check Petitboot-compatible
  src/grub.cfg
Labels: approved, lgtm

#2008 generate-release-meta: Various fixes
  src/cmd-generate-release-meta
Labels: approved, lgtm

#2010 docs: Fix build-process.svg linking in building-fcos.md
  docs/building-fcos.md
Labels: approved, lgtm, needs-ok-to-test

#2012 docs: Use fixed img path to workaround GitHub/Jekyll rendering
  docs/build-process-mermaid.md
  docs/building-fcos.md
Labels: approved, lgtm

#2013 cmd-generate-release-meta: fix field name
  src/cmd-generate-release-meta
Labels: approved, lgtm

#2011 kola/tests/upgrade: bump delay between Zincati checks
  mantle/kola/tests/upgrade/basic.go
Labels: approved, lgtm

#2015 testiso: update mk-s390image path
  mantle/platform/metal.go
Labels: approved, lgtm

#2014 build.sh: freeze kernel to 5.9.16-200.fc33
  build.sh
Labels: approved, lgtm

#2017 [4.6] build.sh: freeze kernel to 5.9.16-100.fc32
  build.sh
Labels: approved, lgtm

#2016 cmd-artifact-disk: fix cosa artifact-disk manual
  src/cmd-artifact-disk
Labels: approved, lgtm, ok-to-test

#2018 Add uncompressed-sha256 to release -> stream translation
  mantle/go.mod
  mantle/go.sum
  mantle/vendor/github.com/coreos/stream-metadata-go/release/release.go
  mantle/vendor/github.com/coreos/stream-metadata-go/release/translate.go
  mantle/vendor/github.com/coreos/stream-metadata-go/stream/stream.go
  mantle/vendor/modules.txt
  src/cmd-generate-release-meta
Labels: approved, lgtm

#2022 gangplank: fix runtime panic in unbounded pod mode
  gangplank/ocp/worker.go
Labels: approved, lgtm

#2024 mantle: Update stream-metadata-go, use arch API
  mantle/go.mod
  mantle/go.sum
  mantle/system/arch.go
  mantle/vendor/github.com/coreos/stream-metadata-go/arch/arch.go
  mantle/vendor/github.com/coreos/stream-metadata-go/stream/stream_utils.go
  mantle/vendor/modules.txt
Labels: approved, lgtm

#2027 cmd-build-fast: Keep metadata from previous commit
  src/cmd-build-fast
Labels: approved, lgtm

#2025 Fully drop support for building images with root-on-LUKS
  src/cmd-buildextend-live
  src/create_disk.sh
  src/gf-fsck
  src/libguestfish.sh
  src/osmet-pack
Labels: approved, lgtm
