Repository coreos/coreos-assembler, pull requests merged in 2022-02, with the labels that each got.

#2678 cmd-buildupload: Add flag for s3 server selection
  src/cmd-buildupload
Labels: ok-to-test

#2679 cmd-buildupload: refactor s3 client
  src/cmd-buildupload
Labels: ok-to-test

#2702 Dockerfile: bump nocache line 🪴
  Dockerfile
Labels: ok-to-test

#2709 Dockerfile: bump nocache line 🪴
  Dockerfile
Labels: ok-to-test

#2713 Dockerfile: bump nocache line 🪴
  Dockerfile
Labels: needs-ok-to-test

#2727 [rhcos-4.10] oscontainer: Push in v2s2 format by default
  src/cmd-upload-oscontainer
  src/oscontainer.py
Labels: branch/rhcos

#2730 [rhcos-4.7] oscontainer: Push in v2s2 format by default
  src/cmd-upload-oscontainer
  src/oscontainer.py
Labels: branch/rhcos
